import { defaultConfig } from 'utils/loadConfig';
import {
  NOTATION_JUNKER,
  NOTATION_ZEMA,
  TYPE_EXTERNAL,
  TYPE_INTERNAL,
} from 'utils/constants';

import { FormState, RenderFieldProps } from './interface';

export const initialState: FormState = {
  notationPattern: {
    value: defaultConfig.cnc.notationPattern,
    options: [
      { label: 'Zema', value: NOTATION_ZEMA },
      { label: 'Junker', value: NOTATION_JUNKER },
    ],
    error: false,
    message: undefined,
  },
  hasBAxis: {
    value: defaultConfig.cnc.hasBAxis,
    options: [
      { label: 'Não', value: 0 },
      { label: 'Sim', value: 1 },
    ],
    error: false,
    message: undefined,
  },
  tool1Var: {
    value: defaultConfig.tools.tool1Var,
    options: [
      { label: 'Inexistente', value: 0 },
      { label: 'Externo', value: TYPE_EXTERNAL },
      { label: 'Interno', value: TYPE_INTERNAL },
    ],
    error: false,
    message: undefined,
  },
  tool1fixedDiamondQtd: {
    value: defaultConfig.tools.tool1fixedDiamondQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
    error: false,
    message: undefined,
  },
  tool1refractableDiamondQtd: {
    value: defaultConfig.tools.tool1refractableDiamondQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
    error: false,
    message: undefined,
  },
  tool1dressingDiscQtd: {
    value: defaultConfig.tools.tool1dressingDiscQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
    error: false,
    message: undefined,
  },
  tool1fixedDressingRollerQtd: {
    value: defaultConfig.tools.tool1fixedDressingRollerQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
    error: false,
    message: undefined,
  },
  tool1sCtrlMovableDressingRollerQtd: {
    value: defaultConfig.tools.tool1sCtrlMovableDressingRollerQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
    error: false,
    message: undefined,
  },
  tool2Var: {
    value: defaultConfig.tools.tool2Var,
    options: [
      { label: 'Inexistente', value: 0 },
      { label: 'Externo', value: TYPE_EXTERNAL },
      { label: 'Interno', value: TYPE_INTERNAL },
    ],
    error: false,
    message: undefined,
  },
  tool2fixedDiamondQtd: {
    value: defaultConfig.tools.tool2fixedDiamondQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
    error: false,
    message: undefined,
  },
  tool2refractableDiamondQtd: {
    value: defaultConfig.tools.tool2refractableDiamondQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
    error: false,
    message: undefined,
  },
  tool2dressingDiscQtd: {
    value: defaultConfig.tools.tool2dressingDiscQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
    error: false,
    message: undefined,
  },
  tool2fixedDressingRollerQtd: {
    value: defaultConfig.tools.tool2fixedDressingRollerQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
    error: false,
    message: undefined,
  },
  tool2sCtrlMovableDressingRollerQtd: {
    value: defaultConfig.tools.tool2sCtrlMovableDressingRollerQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
    error: false,
    message: undefined,
  },
  tool3Var: {
    value: defaultConfig.tools.tool3Var,
    options: [
      { label: 'Inexistente', value: 0 },
      { label: 'Externo', value: TYPE_EXTERNAL },
      { label: 'Interno', value: TYPE_INTERNAL },
    ],
    error: false,
    message: undefined,
  },
  tool3fixedDiamondQtd: {
    value: defaultConfig.tools.tool3fixedDiamondQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
    error: false,
    message: undefined,
  },
  tool3refractableDiamondQtd: {
    value: defaultConfig.tools.tool3refractableDiamondQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
    error: false,
    message: undefined,
  },
  tool3dressingDiscQtd: {
    value: defaultConfig.tools.tool3dressingDiscQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
    error: false,
    message: undefined,
  },
  tool3fixedDressingRollerQtd: {
    value: defaultConfig.tools.tool3fixedDressingRollerQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
    error: false,
    message: undefined,
  },
  tool3sCtrlMovableDressingRollerQtd: {
    value: defaultConfig.tools.tool3sCtrlMovableDressingRollerQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
    error: false,
    message: undefined,
  },
  tool4Var: {
    value: defaultConfig.tools.tool4Var,
    options: [
      { label: 'Inexistente', value: 0 },
      { label: 'Externo', value: TYPE_EXTERNAL },
      { label: 'Interno', value: TYPE_INTERNAL },
    ],
    error: false,
    message: undefined,
  },
  tool4fixedDiamondQtd: {
    value: defaultConfig.tools.tool4fixedDiamondQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
    error: false,
    message: undefined,
  },
  tool4refractableDiamondQtd: {
    value: defaultConfig.tools.tool4refractableDiamondQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
    error: false,
    message: undefined,
  },
  tool4dressingDiscQtd: {
    value: defaultConfig.tools.tool4dressingDiscQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
    error: false,
    message: undefined,
  },
  tool4fixedDressingRollerQtd: {
    value: defaultConfig.tools.tool4fixedDressingRollerQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
    error: false,
    message: undefined,
  },
  tool4sCtrlMovableDressingRollerQtd: {
    value: defaultConfig.tools.tool4sCtrlMovableDressingRollerQtd,
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
    error: false,
    message: undefined,
  },
};

export const fieldsProps: RenderFieldProps = [
  {
    label: 'Padrão de Notação (Zema ou Junker)',
    name: 'notationPattern',
    type: 'number',
    placeholder: '0 ou 1',
    options: [
      { label: 'Zema', value: NOTATION_ZEMA },
      { label: 'Junker', value: NOTATION_JUNKER },
    ],
  },
  {
    label: 'Possui Eixo B',
    name: 'hasBAxis',
    type: 'number',
    placeholder: '50010',
    options: [
      { label: 'Não', value: 0 },
      { label: 'Sim', value: 1 },
    ],
  },
  {
    label: 'Tipo do Rebolo 1',
    name: 'tool1Var',
    type: 'number',
    placeholder: '50010',
    options: [
      { label: 'Inexistente', value: 0 },
      { label: 'Externo', value: TYPE_EXTERNAL },
      { label: 'Interno', value: TYPE_INTERNAL },
    ],
  },
  {
    label: 'Qtd. Diamante Fixo do Rebolo 1',
    name: 'tool1fixedDiamondQtd',
    type: 'number',
    placeholder: '50011',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
  },
  {
    label: 'Qtd. Diamante Abatível do Rebolo 1',
    name: 'tool1refractableDiamondQtd',
    type: 'number',
    placeholder: '50012',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
  },
  {
    label: 'Qtd. Disco Dressador do Rebolo 1',
    name: 'tool1dressingDiscQtd',
    type: 'number',
    placeholder: '50013',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
  },
  {
    label: 'Qtd. Rolo Dressador Fixo do Rebolo 1',
    name: 'tool1fixedDressingRollerQtd',
    type: 'number',
    placeholder: '50014',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
  },
  {
    label: 'Qtd. Rolo Dressador Móvel c/ Servo do Rebolo 1',
    name: 'tool1sCtrlMovableDressingRollerQtd',
    type: 'number',
    placeholder: '50015',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
  },
  {
    label: 'Tipo do Rebolo 2',
    name: 'tool2Var',
    type: 'number',
    placeholder: '50020',
    options: [
      { label: 'Inexistente', value: 0 },
      { label: 'Externo', value: TYPE_EXTERNAL },
      { label: 'Interno', value: TYPE_INTERNAL },
    ],
  },
  {
    label: 'Qtd. Diamante Fixo do Rebolo 2',
    name: 'tool2fixedDiamondQtd',
    type: 'number',
    placeholder: '50021',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
  },
  {
    label: 'Qtd. Diamante Abatível do Rebolo 2',
    name: 'tool2refractableDiamondQtd',
    type: 'number',
    placeholder: '50022',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
  },
  {
    label: 'Qtd. Disco Dressador do Rebolo 2',
    name: 'tool2dressingDiscQtd',
    type: 'number',
    placeholder: '50023',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
  },
  {
    label: 'Qtd. Rolo Dressador Fixo do Rebolo 2',
    name: 'tool2fixedDressingRollerQtd',
    type: 'number',
    placeholder: '50024',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
  },
  {
    label: 'Qtd. Rolo Dressador Móvel c/ Servo do Rebolo 2',
    name: 'tool2sCtrlMovableDressingRollerQtd',
    type: 'number',
    placeholder: '50025',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
  },
  {
    label: 'Tipo do Rebolo 3',
    name: 'tool3Var',
    type: 'number',
    placeholder: '50030',
    options: [
      { label: 'Inexistente', value: 0 },
      { label: 'Externo', value: TYPE_EXTERNAL },
      { label: 'Interno', value: TYPE_INTERNAL },
    ],
  },
  {
    label: 'Qtd. Diamante Fixo do Rebolo 3',
    name: 'tool3fixedDiamondQtd',
    type: 'number',
    placeholder: '50031',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
  },
  {
    label: 'Qtd. Diamante Abatível do Rebolo 3',
    name: 'tool3refractableDiamondQtd',
    type: 'number',
    placeholder: '50032',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
  },
  {
    label: 'Qtd. Disco Dressador do Rebolo 3',
    name: 'tool3dressingDiscQtd',
    type: 'number',
    placeholder: '50033',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
  },
  {
    label: 'Qtd. Rolo Dressador Fixo do Rebolo 3',
    name: 'tool3fixedDressingRollerQtd',
    type: 'number',
    placeholder: '50034',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
  },
  {
    label: 'Qtd. Rolo Dressador Móvel c/ Servo do Rebolo 3',
    name: 'tool3sCtrlMovableDressingRollerQtd',
    type: 'number',
    placeholder: '50035',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
  },
  {
    label: 'Tipo do Rebolo 4',
    name: 'tool4Var',
    type: 'number',
    placeholder: '50040',
    options: [
      { label: 'Inexistente', value: 0 },
      { label: 'Externo', value: TYPE_EXTERNAL },
      { label: 'Interno', value: TYPE_INTERNAL },
    ],
  },
  {
    label: 'Qtd. Diamante Fixo do Rebolo 4',
    name: 'tool4fixedDiamondQtd',
    type: 'number',
    placeholder: '50041',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
  },
  {
    label: 'Qtd. Diamante Abatível do Rebolo 4',
    name: 'tool4refractableDiamondQtd',
    type: 'number',
    placeholder: '50042',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
      { label: '3', value: 3 },
      { label: '4', value: 4 },
    ],
  },
  {
    label: 'Qtd. Disco Dressador do Rebolo 4',
    name: 'tool4dressingDiscQtd',
    type: 'number',
    placeholder: '50043',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
  },
  {
    label: 'Qtd. Rolo Dressador Fixo do Rebolo 4',
    name: 'tool4fixedDressingRollerQtd',
    type: 'number',
    placeholder: '50044',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
  },
  {
    label: 'Qtd. Rolo Dressador Móvel c/ Servo do Rebolo 4',
    name: 'tool4sCtrlMovableDressingRollerQtd',
    type: 'number',
    placeholder: '50045',
    options: [
      { label: '0', value: 0 },
      { label: '1', value: 1 },
      { label: '2', value: 2 },
    ],
  },
];
